jobs:
  build:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Download BackportBot
      run: wget https://github.com/spring-io/backport-bot/releases/download/latest/backport-bot-0.0.1-SNAPSHOT.jar
    - continue-on-error: true
      env:
        GITHUB_EVENT: ${{ toJSON(github.event) }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Backport
      run: java -jar backport-bot-0.0.1-SNAPSHOT.jar --github.accessToken="$GITHUB_TOKEN"
        --github.event_name "$GITHUB_EVENT_NAME" --github.event "$GITHUB_EVENT"
name: Backport Bot
on:
  repository_dispatch:
    types: trigger-ga___backport-bot.yml
permissions:
  contents: read
